export type Post = {
  slug: string;
  category: string;
  title: string;
  excerpt: string;
  readTime: string;
  difficulty: string;
  tags: string[];
};

export const posts: Post[] = [
  {
    slug: "hot-neutral-ground",
    category: "ELECTRICAL",
    title: "Hot wire, neutral wire, ground wire",
    excerpt: "Ribbed = neutral. Smooth = hot. Green or bare copper = ground. This is the single most useful thing you can know before touching a wire.",
    readTime: "5 MIN READ",
    difficulty: "BEGINNER",
    tags: ["ELECTRICAL SAFETY"],
  },
  {
    slug: "right-to-remain-silent",
    category: "LEGAL",
    title: "You don't have to answer that",
    excerpt: "What you're actually required to say to police, what you're not, and why staying silent is almost always the right move.",
    readTime: "4 MIN READ",
    difficulty: "BEGINNER",
    tags: ["KNOW YOUR RIGHTS"],
  },
  {
    slug: "er-vs-urgent-care",
    category: "HEALTH",
    title: "ER vs urgent care vs your doctor",
    excerpt: "The difference costs hundreds or thousands of dollars depending on which door you walk through.",
    readTime: "6 MIN READ",
    difficulty: "INTERMEDIATE",
    tags: ["HEALTHCARE"],
  },
  {
    slug: "landlord-rights",
    category: "HOME",
    title: "Your landlord cannot do that",
    excerpt: "Entry without notice, withholding deposits, retaliation for complaints — what's actually illegal in most states.",
    readTime: "5 MIN READ",
    difficulty: "BEGINNER",
    tags: ["TENANT RIGHTS"],
  },
  {
    slug: "how-interest-works",
    category: "FINANCE",
    title: "How interest actually works against you",
    excerpt: "APR vs APY, minimum payments as debt traps, and why paying $25 extra a month matters more than you think.",
    readTime: "7 MIN READ",
    difficulty: "INTERMEDIATE",
    tags: ["PERSONAL FINANCE"],
  },
  {
    slug: "breaker-box-basics",
    category: "ELECTRICAL",
    title: "Breaker box basics",
    excerpt: "Your breaker box controls every circuit in your house. Knowing how it works means you can troubleshoot problems yourself.",
    readTime: "4 MIN READ",
    difficulty: "BEGINNER",
    tags: ["ELECTRICAL"],
  },
  // ELECTRICAL
  {
    slug: "gfci-afci-outlets",
    category: "ELECTRICAL",
    title: "GFCI vs AFCI outlets",
    excerpt: "The outlets with the test/reset buttons aren't just a quirk — they're code-required life safety devices. Here's what each one protects against and where they're legally required.",
    readTime: "5 MIN READ",
    difficulty: "BEGINNER",
    tags: ["ELECTRICAL SAFETY"],
  },
  {
    slug: "extension-cord-gauge",
    category: "ELECTRICAL",
    title: "Why your extension cord might be a fire hazard",
    excerpt: "The thinner the cord, the more resistance, the more heat. AWG numbers go backwards. A 16-gauge cord running a space heater is how house fires start.",
    readTime: "4 MIN READ",
    difficulty: "BEGINNER",
    tags: ["ELECTRICAL SAFETY"],
  },
  {
    slug: "outlet-replacement",
    category: "ELECTRICAL",
    title: "How to replace an outlet",
    excerpt: "Replacing a standard 15A outlet is one of the simplest electrical jobs you can do yourself. The part costs $1. The steps are the same every time.",
    readTime: "6 MIN READ",
    difficulty: "INTERMEDIATE",
    tags: ["DIY", "ELECTRICAL"],
  },
  {
    slug: "smoke-co-detector-placement",
    category: "ELECTRICAL",
    title: "Where smoke and CO detectors are legally required",
    excerpt: "Most people put them in the wrong spots. The code requirements exist because where you place them determines whether they work.",
    readTime: "4 MIN READ",
    difficulty: "BEGINNER",
    tags: ["HOME SAFETY"],
  },
  // LEGAL
  {
    slug: "recording-police",
    category: "LEGAL",
    title: "You can record police in public",
    excerpt: "It's a First Amendment right upheld by every federal circuit court. There are limits and context matters, but the baseline is clear: you can film officers doing their jobs.",
    readTime: "5 MIN READ",
    difficulty: "BEGINNER",
    tags: ["KNOW YOUR RIGHTS"],
  },
  {
    slug: "small-claims-court",
    category: "LEGAL",
    title: "Small claims court actually works",
    excerpt: "Security deposit stolen, contractor ghosted, someone owes you money — small claims is designed for exactly this. No lawyer needed. Filing costs $30–100.",
    readTime: "7 MIN READ",
    difficulty: "INTERMEDIATE",
    tags: ["CIVIL LAW"],
  },
  {
    slug: "probable-cause",
    category: "LEGAL",
    title: "What probable cause actually means",
    excerpt: "It's not just 'they had a reason.' Probable cause is a legal standard that determines whether a search, arrest, or stop is constitutional. Most people have no idea where the line is.",
    readTime: "5 MIN READ",
    difficulty: "INTERMEDIATE",
    tags: ["KNOW YOUR RIGHTS"],
  },
  {
    slug: "non-compete-agreements",
    category: "LEGAL",
    title: "Non-compete agreements are mostly unenforceable",
    excerpt: "Most non-competes are overbroad, unenforceable, or outright illegal in your state. They're designed to scare you. Here's what courts actually look at.",
    readTime: "6 MIN READ",
    difficulty: "INTERMEDIATE",
    tags: ["EMPLOYMENT LAW"],
  },
  // HEALTH
  {
    slug: "generic-vs-brand-drugs",
    category: "HEALTH",
    title: "Generic drugs are the same drug",
    excerpt: "Same active ingredient, same dosage, same clinical effect. The FDA requires it. Brand names cost 80–85% more for the same molecule.",
    readTime: "4 MIN READ",
    difficulty: "BEGINNER",
    tags: ["MEDICATION"],
  },
  {
    slug: "insurance-terms-decoded",
    category: "HEALTH",
    title: "Deductible, copay, out-of-pocket max — decoded",
    excerpt: "These three numbers determine what you actually pay. Most people don't understand how they interact until they get a surprise bill.",
    readTime: "6 MIN READ",
    difficulty: "BEGINNER",
    tags: ["HEALTH INSURANCE"],
  },
  {
    slug: "prescription-cash-prices",
    category: "HEALTH",
    title: "Sometimes cash is cheaper than your insurance",
    excerpt: "GoodRx, Cost Plus Drugs, and pharmacy cash prices can be dramatically lower than your insurance copay. The system isn't designed to tell you this.",
    readTime: "5 MIN READ",
    difficulty: "BEGINNER",
    tags: ["MEDICATION", "HEALTHCARE"],
  },
  {
    slug: "reading-lab-results",
    category: "HEALTH",
    title: "How to read your own lab results",
    excerpt: "You're legally entitled to your own lab work. The reference ranges are on the page. Here's what the common panels actually measure and what out-of-range means.",
    readTime: "8 MIN READ",
    difficulty: "INTERMEDIATE",
    tags: ["HEALTHCARE"],
  },
  // HOME
  {
    slug: "water-shutoff-locations",
    category: "HOME",
    title: "Find every water shutoff in your home before you need it",
    excerpt: "A burst pipe gives you seconds to act. The main shutoff, toilet shutoff, sink shutoffs — know where they are before water is spraying at your ceiling.",
    readTime: "4 MIN READ",
    difficulty: "BEGINNER",
    tags: ["HOME MAINTENANCE"],
  },
  {
    slug: "lease-clauses",
    category: "HOME",
    title: "Lease clauses that can actually hurt you",
    excerpt: "Automatic renewal, joint and several liability, early termination fees, lease modification clauses — these are the parts people skip that cost them money.",
    readTime: "6 MIN READ",
    difficulty: "INTERMEDIATE",
    tags: ["TENANT RIGHTS"],
  },
  {
    slug: "mold-habitability",
    category: "HOME",
    title: "Mold, habitability, and what your landlord is required to do",
    excerpt: "Mold from a leak your landlord ignored is not your problem to fix. Here's the legal standard, how to document it, and what remedies you have.",
    readTime: "5 MIN READ",
    difficulty: "INTERMEDIATE",
    tags: ["TENANT RIGHTS", "HOME SAFETY"],
  },
  {
    slug: "renters-insurance",
    category: "HOME",
    title: "Renters insurance covers more than you think and costs less than you think",
    excerpt: "Your landlord's insurance doesn't cover your stuff. Renters insurance is $12–20/month and covers theft, fire, water damage, and liability — including if your dog bites someone.",
    readTime: "5 MIN READ",
    difficulty: "BEGINNER",
    tags: ["INSURANCE"],
  },
  // FINANCE
  {
    slug: "credit-score-factors",
    category: "FINANCE",
    title: "What actually moves your credit score",
    excerpt: "Five factors, specific weights. Payment history is 35% alone. Most people optimize for the wrong things while ignoring the ones that matter most.",
    readTime: "6 MIN READ",
    difficulty: "BEGINNER",
    tags: ["CREDIT"],
  },
  {
    slug: "medical-bill-negotiation",
    category: "FINANCE",
    title: "Hospital bills are negotiable",
    excerpt: "The chargemaster price is fiction. Hospitals write off debt constantly. If you know the system, you can reduce a $10,000 bill to something survivable.",
    readTime: "7 MIN READ",
    difficulty: "INTERMEDIATE",
    tags: ["HEALTHCARE", "NEGOTIATION"],
  },
  {
    slug: "401k-employer-match",
    category: "FINANCE",
    title: "Your employer match is free money you might be leaving behind",
    excerpt: "A 3% employer match on a $50k salary is $1,500/year you're declining if you don't contribute enough to get it. Here's how matching works and how vesting can trap you.",
    readTime: "5 MIN READ",
    difficulty: "BEGINNER",
    tags: ["RETIREMENT", "PERSONAL FINANCE"],
  },
  {
    slug: "pay-stub-decoded",
    category: "FINANCE",
    title: "What every line on your pay stub means",
    excerpt: "Gross vs net, FICA, federal and state withholding, pre-tax deductions — most people just look at the bottom number. The rest tells you how much you're actually earning.",
    readTime: "5 MIN READ",
    difficulty: "BEGINNER",
    tags: ["TAXES", "PERSONAL FINANCE"],
  },
  {
    slug: "salary-negotiation",
    category: "FINANCE",
    title: "How to actually negotiate your salary",
    excerpt: "Most people never negotiate. The ones who do earn hundreds of thousands more over a career. The first number, the silence, the counter — it's all learnable.",
    readTime: "6 MIN READ",
    difficulty: "INTERMEDIATE",
    tags: ["NEGOTIATION", "PERSONAL FINANCE"],
  },
  {
    slug: "emergency-fund-basics",
    category: "FINANCE",
    title: "How much emergency fund you actually need, and where to put it",
    excerpt: "Not a number pulled from thin air — three to six months of essential expenses, in an account you can access same-day, not the stock market.",
    readTime: "5 MIN READ",
    difficulty: "BEGINNER",
    tags: ["PERSONAL FINANCE"],
  },
  {
    slug: "credit-freeze-vs-lock",
    category: "FINANCE",
    title: "Credit freeze vs credit lock — one is free and federally guaranteed, one isn't",
    excerpt: "A credit freeze is free by law at all three bureaus and blocks new accounts from opening in your name. A credit lock is a paid convenience product with weaker protections.",
    readTime: "5 MIN READ",
    difficulty: "BEGINNER",
    tags: ["CREDIT"],
  },
  // ELECTRICAL (additional)
  {
    slug: "surge-protector-vs-power-strip",
    category: "ELECTRICAL",
    title: "Surge protector vs power strip — they are not the same thing",
    excerpt: "A power strip just adds outlets. A surge protector absorbs voltage spikes before they reach your electronics. Plugging your computer into the wrong one won't save it.",
    readTime: "4 MIN READ",
    difficulty: "BEGINNER",
    tags: ["ELECTRICAL SAFETY"],
  },
  {
    slug: "amperage-vs-wattage",
    category: "ELECTRICAL",
    title: "Amps, volts, watts — the math that tells you what a circuit can handle",
    excerpt: "Volts times amps equals watts. That's it. Once you know that, you can figure out why your breaker trips and what you can safely plug in.",
    readTime: "5 MIN READ",
    difficulty: "BEGINNER",
    tags: ["ELECTRICAL"],
  },
  // LEGAL (additional)
  {
    slug: "miranda-rights-when",
    category: "LEGAL",
    title: "Miranda rights only apply when police do one specific thing",
    excerpt: "Getting arrested doesn't trigger Miranda. Police only have to read you your rights before a custodial interrogation — and not reading them isn't the free pass TV makes it look like.",
    readTime: "5 MIN READ",
    difficulty: "INTERMEDIATE",
    tags: ["KNOW YOUR RIGHTS"],
  },
  {
    slug: "statute-of-limitations-basics",
    category: "LEGAL",
    title: "Statute of limitations: the clock that resets if you're not careful",
    excerpt: "Old debt can become legally uncollectible — until you acknowledge it or make a partial payment, which can restart the clock in many states. Debt collectors know this even when you don't.",
    readTime: "6 MIN READ",
    difficulty: "INTERMEDIATE",
    tags: ["CIVIL LAW"],
  },
  // HEALTH (additional)
  {
    slug: "epipen-cost-alternatives",
    category: "HEALTH",
    title: "Your EpiPen alternative might be a different device entirely",
    excerpt: "Generic epinephrine auto-injectors can cost hundreds less, but some use a different mechanism than the EpiPen. Knowing which device you're holding matters in an emergency.",
    readTime: "5 MIN READ",
    difficulty: "BEGINNER",
    tags: ["MEDICATION"],
  },
  {
    slug: "telehealth-vs-urgent-care",
    category: "HEALTH",
    title: "When a video call is enough, and when it isn't",
    excerpt: "Telehealth is faster and cheaper for a huge range of problems. It's also the wrong choice for a growing number of situations that people default to it for anyway.",
    readTime: "5 MIN READ",
    difficulty: "BEGINNER",
    tags: ["HEALTHCARE"],
  },
  // HOME (additional)
  {
    slug: "space-heater-safety",
    category: "HOME",
    title: "Space heaters cause more house fires than almost anything else you own",
    excerpt: "Three feet of clearance, direct into the wall, never an extension cord. The rules are simple. Most house fires from space heaters happen because someone skipped one of them.",
    readTime: "4 MIN READ",
    difficulty: "BEGINNER",
    tags: ["HOME SAFETY"],
  },
  {
    slug: "home-inventory-for-insurance",
    category: "HOME",
    title: "Your insurance claim is only as good as your home inventory",
    excerpt: "After a fire or a break-in, you have to prove what you owned. A five-minute video walkthrough today is the difference between a paid claim and a fight.",
    readTime: "4 MIN READ",
    difficulty: "BEGINNER",
    tags: ["INSURANCE"],
  },
  // AUTO
  {
    slug: "tire-tread-penny-test",
    category: "AUTO",
    title: "The penny test for tire tread is outdated — here's the better one",
    excerpt: "Lincoln's head showing means your tires were already dangerous. The quarter test catches the problem sooner, and tread wear bars are built into every tire for a reason.",
    readTime: "4 MIN READ",
    difficulty: "BEGINNER",
    tags: ["CAR MAINTENANCE"],
  },
  {
    slug: "check-engine-light-codes",
    category: "AUTO",
    title: "That check engine light isn't automatically a $1,000 problem",
    excerpt: "Auto parts stores will read the code for free. Knowing the code before you go to a mechanic is the difference between an informed conversation and getting quoted whatever they think you'll pay.",
    readTime: "5 MIN READ",
    difficulty: "BEGINNER",
    tags: ["CAR MAINTENANCE"],
  },
  {
    slug: "extended-warranties-scam",
    category: "AUTO",
    title: "That 'your vehicle warranty is about to expire' call isn't from your dealer",
    excerpt: "Third-party vehicle service contracts are sold as warranties, aren't, and are one of the most reported scams in the country. Here's how to tell a legitimate extended warranty from a scam.",
    readTime: "6 MIN READ",
    difficulty: "INTERMEDIATE",
    tags: ["CONSUMER PROTECTION"],
  },
  {
    slug: "lemon-law-basics",
    category: "AUTO",
    title: "Lemon laws exist for exactly the car you're dealing with",
    excerpt: "A new car that's been in the shop for the same defect multiple times, or out of service too many days, may legally entitle you to a refund or replacement. Most people never file.",
    readTime: "6 MIN READ",
    difficulty: "INTERMEDIATE",
    tags: ["CONSUMER PROTECTION"],
  },
  // TECH
  {
    slug: "password-manager-2fa",
    category: "TECH",
    title: "One reused password is how your whole digital life gets taken",
    excerpt: "A password manager plus two-factor authentication closes off the two most common ways accounts get compromised. Neither takes more than twenty minutes to set up.",
    readTime: "6 MIN READ",
    difficulty: "BEGINNER",
    tags: ["DIGITAL SECURITY"],
  },
  {
    slug: "phishing-red-flags",
    category: "TECH",
    title: "The tells that give away almost every phishing attempt",
    excerpt: "Urgency, a mismatched sender address, and a link that doesn't go where the text says it does. Learn the pattern once and you'll catch it every time after.",
    readTime: "5 MIN READ",
    difficulty: "BEGINNER",
    tags: ["DIGITAL SECURITY"],
  },
  {
    slug: "data-broker-opt-out",
    category: "TECH",
    title: "Companies you've never heard of are selling your home address right now",
    excerpt: "Data brokers compile and sell your personal information legally. You can opt out of most of them — it's just not made easy, and no one tells you it's an option.",
    readTime: "7 MIN READ",
    difficulty: "INTERMEDIATE",
    tags: ["PRIVACY"],
  },
  {
    slug: "public-wifi-vpn-myths",
    category: "TECH",
    title: "The coffee shop hacker stealing your passwords isn't really the threat anymore",
    excerpt: "Most of the web is encrypted by default now, which changes what a VPN actually protects you from on public wifi. It's not nothing — it's just not what the ads say.",
    readTime: "6 MIN READ",
    difficulty: "INTERMEDIATE",
    tags: ["PRIVACY", "DIGITAL SECURITY"],
  },
  // CONSUMER
  {
    slug: "credit-card-chargebacks",
    category: "CONSUMER",
    title: "Credit card disputes and debit card disputes are not the same protection",
    excerpt: "Federal law caps your credit card fraud liability at $50 and gives you real leverage over bad merchants. Debit cards play by different rules, and the clock starts the moment the charge hits.",
    readTime: "6 MIN READ",
    difficulty: "INTERMEDIATE",
    tags: ["CONSUMER PROTECTION"],
  },
  {
    slug: "return-policy-tricks",
    category: "CONSUMER",
    title: "No law says a store has to take your return",
    excerpt: "Return policies are a courtesy, not a legal requirement, with one real federal exception. Knowing which is which changes how you shop and how you argue when a return gets denied.",
    readTime: "5 MIN READ",
    difficulty: "BEGINNER",
    tags: ["CONSUMER PROTECTION"],
  },
  {
    slug: "warranty-vs-insurance",
    category: "CONSUMER",
    title: "'Warranty void if removed' stickers are mostly illegal",
    excerpt: "A federal law from 1975 already settled this: a manufacturer can't void your warranty just because you used a third-party part or an independent repair shop, unless they can prove that part caused the problem.",
    readTime: "6 MIN READ",
    difficulty: "INTERMEDIATE",
    tags: ["CONSUMER PROTECTION"],
  },
  {
    slug: "subscription-cancellation-rights",
    category: "CONSUMER",
    title: "Why canceling a subscription is never as easy as signing up for one",
    excerpt: "It's not your imagination — some states legally require cancellation to be as easy as sign-up, but there's no federal rule yet forcing every company to comply.",
    readTime: "5 MIN READ",
    difficulty: "BEGINNER",
    tags: ["CONSUMER PROTECTION"],
  },
];

export const categories = ["ALL", "ELECTRICAL", "LEGAL", "HEALTH", "HOME", "FINANCE", "AUTO", "TECH", "CONSUMER"];

export function categorySlug(category: string): string {
  return category.toLowerCase();
}

export function categoryFromSlug(slug: string): string | undefined {
  return categories.slice(1).find(c => categorySlug(c) === slug);
}
