export type Post = {
  slug: string;
  category: string;
  title: string;
  excerpt: string;
  readTime: string;
  difficulty: string;
  tags: string[];
};

export const posts: Post[] = [
  // Added Sept. 2026
  {
    slug: "got-scammed-what-now",
    category: "TECH",
    title: "You just got scammed. Here's what to do in the next hour",
    excerpt: "Speed matters more than anything else. Call the company that moved the money, lock down your accounts, report it — and watch out for the second scam that targets victims of the first.",
    readTime: "6 MIN READ",
    difficulty: "BEGINNER",
    tags: ["DIGITAL SECURITY", "CONSUMER PROTECTION"],
  },
  {
    slug: "sim-swap-protection",
    category: "TECH",
    title: "Someone can steal your phone number without touching your phone",
    excerpt: "A SIM swap moves your number to a scammer's phone — and with it, every text-message login code. Every major carrier now has a free lock that stops it. Turn yours on.",
    readTime: "5 MIN READ",
    difficulty: "BEGINNER",
    tags: ["DIGITAL SECURITY"],
  },
  {
    slug: "back-up-your-phone",
    category: "TECH",
    title: "If your phone died today, what would you lose?",
    excerpt: "Photos, contacts, texts, and the two-factor codes you need to get into everything else. Here's how to back up an iPhone or Android — and the step almost everyone forgets.",
    readTime: "5 MIN READ",
    difficulty: "BEGINNER",
    tags: ["DIGITAL SECURITY"],
  },
  {
    slug: "jump-start-a-car",
    category: "AUTO",
    title: "How to jump-start a car without frying anything",
    excerpt: "Red to dead, red to good, black to good, black to bare metal on the dead car — not the dead battery. That last clamp is the one people get wrong.",
    readTime: "4 MIN READ",
    difficulty: "BEGINNER",
    tags: ["CAR MAINTENANCE"],
  },
  {
    slug: "after-a-car-accident",
    category: "AUTO",
    title: "What to do in the first hour after a car accident",
    excerpt: "Safety first, then evidence. What you're legally required to do at the scene, what to photograph, what to say — and the one thing not to say.",
    readTime: "6 MIN READ",
    difficulty: "BEGINNER",
    tags: ["CAR INSURANCE", "KNOW YOUR RIGHTS"],
  },
  {
    slug: "correct-tire-pressure",
    category: "AUTO",
    title: "The number on your tire is the wrong tire pressure",
    excerpt: "The PSI molded into the sidewall is the maximum the tire can hold — not what your car needs. The right number is on a sticker inside the driver's door.",
    readTime: "4 MIN READ",
    difficulty: "BEGINNER",
    tags: ["CAR MAINTENANCE"],
  },
  {
    slug: "dispute-credit-report-errors",
    category: "CONSUMER",
    title: "How to get errors off your credit report — for free",
    excerpt: "You can pull all three reports free every week, dispute anything wrong at no cost, and the bureau has 30 days to investigate. Nobody needs to be paid to do this for you.",
    readTime: "6 MIN READ",
    difficulty: "BEGINNER",
    tags: ["CREDIT", "CONSUMER PROTECTION"],
  },
  {
    slug: "debt-collector-rules",
    category: "CONSUMER",
    title: "What debt collectors legally can't do to you",
    excerpt: "No calls before 8am or after 9pm, no threats, no telling your boss, and they have to stop contacting you if you tell them to in writing. Here's the federal rulebook.",
    readTime: "6 MIN READ",
    difficulty: "BEGINNER",
    tags: ["CONSUMER PROTECTION", "CREDIT"],
  },
  {
    slug: "at-will-employment",
    category: "LEGAL",
    title: "Yes, you can be fired for no reason — but not for these reasons",
    excerpt: "Every state but Montana is \"at will,\" so an employer doesn't need a reason. But firing you for an illegal reason — discrimination, retaliation, jury duty — is a different story.",
    readTime: "6 MIN READ",
    difficulty: "BEGINNER",
    tags: ["EMPLOYMENT LAW", "KNOW YOUR RIGHTS"],
  },
  {
    slug: "w2-vs-1099",
    category: "FINANCE",
    title: "W-2 vs 1099 — why the same paycheck can cost a contractor 7.65% more in tax",
    excerpt: "Employees get taxes withheld and split Social Security and Medicare with their employer. Contractors pay the whole 15.3% themselves, pay quarterly, and owe it whether or not they get a form.",
    readTime: "6 MIN READ",
    difficulty: "INTERMEDIATE",
    tags: ["TAXES", "PERSONAL FINANCE"],
  },
  {
    slug: "health-insurance-after-job-loss",
    category: "HEALTH",
    title: "Lost your job? You have 60 days to sort out health insurance",
    excerpt: "COBRA keeps your exact plan but can cost four figures a month. A Marketplace plan may cost far less. Both have a 60-day window — and choosing wrong can lock you in.",
    readTime: "6 MIN READ",
    difficulty: "BEGINNER",
    tags: ["HEALTH INSURANCE"],
  },
  {
    slug: "frozen-pipes",
    category: "HOME",
    title: "Frozen pipes — how to prevent them, and how to thaw them without a flood",
    excerpt: "A trickle of water, open cabinet doors, and steady heat prevent most frozen pipes. If one freezes, thaw it slowly with the faucet open — and never with a flame.",
    readTime: "5 MIN READ",
    difficulty: "BEGINNER",
    tags: ["HOME MAINTENANCE"],
  },
  // Original posts
  {
    slug: "hot-neutral-ground",
    category: "ELECTRICAL",
    title: "Hot wire, neutral wire, ground wire",
    excerpt: "Ribbed = neutral. Smooth = hot. Green or bare copper = ground. This is the single most useful thing you can know before touching a wire.",
    readTime: "5 MIN READ",
    difficulty: "BEGINNER",
    tags: ["ELECTRICAL SAFETY"],
  },
  {
    slug: "right-to-remain-silent",
    category: "LEGAL",
    title: "You don't have to answer that",
    excerpt: "What you're actually required to say to police, what you're not, and why staying silent is almost always the right move.",
    readTime: "4 MIN READ",
    difficulty: "BEGINNER",
    tags: ["KNOW YOUR RIGHTS"],
  },
  {
    slug: "er-vs-urgent-care",
    category: "HEALTH",
    title: "ER vs urgent care vs your doctor",
    excerpt: "The difference costs hundreds or thousands of dollars depending on which door you walk through.",
    readTime: "6 MIN READ",
    difficulty: "INTERMEDIATE",
    tags: ["HEALTHCARE"],
  },
  {
    slug: "landlord-rights",
    category: "HOME",
    title: "Your landlord cannot do that",
    excerpt: "Entry without notice, withholding deposits, retaliation for complaints — what's actually illegal in most states.",
    readTime: "5 MIN READ",
    difficulty: "BEGINNER",
    tags: ["TENANT RIGHTS"],
  },
  {
    slug: "how-interest-works",
    category: "FINANCE",
    title: "How interest actually works against you",
    excerpt: "APR vs APY, minimum payments as debt traps, and why paying $25 extra a month matters more than you think.",
    readTime: "7 MIN READ",
    difficulty: "INTERMEDIATE",
    tags: ["PERSONAL FINANCE"],
  },
  {
    slug: "breaker-box-basics",
    category: "ELECTRICAL",
    title: "Breaker box basics",
    excerpt: "Your breaker box controls every circuit in your house. Knowing how it works means you can troubleshoot problems yourself.",
    readTime: "4 MIN READ",
    difficulty: "BEGINNER",
    tags: ["ELECTRICAL"],
  },
  // ELECTRICAL
  {
    slug: "gfci-afci-outlets",
    category: "ELECTRICAL",
    title: "GFCI vs AFCI outlets",
    excerpt: "The outlets with the test/reset buttons aren't just a quirk — they're code-required life safety devices. Here's what each one protects against and where they're legally required.",
    readTime: "5 MIN READ",
    difficulty: "BEGINNER",
    tags: ["ELECTRICAL SAFETY"],
  },
  {
    slug: "extension-cord-gauge",
    category: "ELECTRICAL",
    title: "Why your extension cord might be a fire hazard",
    excerpt: "The thinner the cord, the more resistance, the more heat. AWG numbers go backwards. A 16-gauge cord running a space heater is how house fires start.",
    readTime: "4 MIN READ",
    difficulty: "BEGINNER",
    tags: ["ELECTRICAL SAFETY"],
  },
  {
    slug: "outlet-replacement",
    category: "ELECTRICAL",
    title: "How to replace an outlet",
    excerpt: "Replacing a standard 15A outlet is one of the simplest electrical jobs you can do yourself. The part costs $1. The steps are the same every time.",
    readTime: "6 MIN READ",
    difficulty: "INTERMEDIATE",
    tags: ["DIY", "ELECTRICAL"],
  },
  {
    slug: "smoke-co-detector-placement",
    category: "ELECTRICAL",
    title: "Where smoke and CO detectors are legally required",
    excerpt: "Most people put them in the wrong spots. The code requirements exist because where you place them determines whether they work.",
    readTime: "4 MIN READ",
    difficulty: "BEGINNER",
    tags: ["HOME SAFETY"],
  },
  // LEGAL
  {
    slug: "recording-police",
    category: "LEGAL",
    title: "You can record police in public",
    excerpt: "It's a First Amendment right upheld by every federal circuit court. There are limits and context matters, but the baseline is clear: you can film officers doing their jobs.",
    readTime: "5 MIN READ",
    difficulty: "BEGINNER",
    tags: ["KNOW YOUR RIGHTS"],
  },
  {
    slug: "small-claims-court",
    category: "LEGAL",
    title: "Small claims court actually works",
    excerpt: "Security deposit stolen, contractor ghosted, someone owes you money — small claims is designed for exactly this. No lawyer needed. Filing costs $30–100.",
    readTime: "7 MIN READ",
    difficulty: "INTERMEDIATE",
    tags: ["CIVIL LAW"],
  },
  {
    slug: "probable-cause",
    category: "LEGAL",
    title: "What probable cause actually means",
    excerpt: "It's not just 'they had a reason.' Probable cause is a legal standard that determines whether a search, arrest, or stop is constitutional. Most people have no idea where the line is.",
    readTime: "5 MIN READ",
    difficulty: "INTERMEDIATE",
    tags: ["KNOW YOUR RIGHTS"],
  },
  {
    slug: "non-compete-agreements",
    category: "LEGAL",
    title: "Non-compete agreements are mostly unenforceable",
    excerpt: "Most non-competes are overbroad, unenforceable, or outright illegal in your state. They're designed to scare you. Here's what courts actually look at.",
    readTime: "6 MIN READ",
    difficulty: "INTERMEDIATE",
    tags: ["EMPLOYMENT LAW"],
  },
  // HEALTH
  {
    slug: "generic-vs-brand-drugs",
    category: "HEALTH",
    title: "Generic drugs are the same drug",
    excerpt: "Same active ingredient, same dosage, same clinical effect. The FDA requires it. Generics typically cost 80–85% less for the same molecule.",
    readTime: "4 MIN READ",
    difficulty: "BEGINNER",
    tags: ["MEDICATION"],
  },
  {
    slug: "insurance-terms-decoded",
    category: "HEALTH",
    title: "Deductible, copay, out-of-pocket max — decoded",
    excerpt: "These three numbers determine what you actually pay. Most people don't understand how they interact until they get a surprise bill.",
    readTime: "6 MIN READ",
    difficulty: "BEGINNER",
    tags: ["HEALTH INSURANCE"],
  },
  {
    slug: "prescription-cash-prices",
    category: "HEALTH",
    title: "Sometimes cash is cheaper than your insurance",
    excerpt: "GoodRx, Cost Plus Drugs, and pharmacy cash prices can be dramatically lower than your insurance copay. The system isn't designed to tell you this.",
    readTime: "5 MIN READ",
    difficulty: "BEGINNER",
    tags: ["MEDICATION", "HEALTHCARE"],
  },
  {
    slug: "reading-lab-results",
    category: "HEALTH",
    title: "How to read your own lab results",
    excerpt: "You're legally entitled to your own lab work. The reference ranges are on the page. Here's what the common panels actually measure and what out-of-range means.",
    readTime: "8 MIN READ",
    difficulty: "INTERMEDIATE",
    tags: ["HEALTHCARE"],
  },
  // HOME
  {
    slug: "water-shutoff-locations",
    category: "HOME",
    title: "Find every water shutoff in your home before you need it",
    excerpt: "A burst pipe gives you seconds to act. The main shutoff, toilet shutoff, sink shutoffs — know where they are before water is spraying at your ceiling.",
    readTime: "4 MIN READ",
    difficulty: "BEGINNER",
    tags: ["HOME MAINTENANCE"],
  },
  {
    slug: "lease-clauses",
    category: "HOME",
    title: "Lease clauses that can actually hurt you",
    excerpt: "Automatic renewal, joint and several liability, early termination fees, lease modification clauses — these are the parts people skip that cost them money.",
    readTime: "6 MIN READ",
    difficulty: "INTERMEDIATE",
    tags: ["TENANT RIGHTS"],
  },
  {
    slug: "mold-habitability",
    category: "HOME",
    title: "Mold, habitability, and what your landlord is required to do",
    excerpt: "Mold from a leak your landlord ignored is not your problem to fix. Here's the legal standard, how to document it, and what remedies you have.",
    readTime: "5 MIN READ",
    difficulty: "INTERMEDIATE",
    tags: ["TENANT RIGHTS", "HOME SAFETY"],
  },
  {
    slug: "renters-insurance",
    category: "HOME",
    title: "Renters insurance covers more than you think and costs less than you think",
    excerpt: "Your landlord's insurance doesn't cover your stuff. Renters insurance is $12–20/month and covers theft, fire, water damage, and liability — including if your dog bites someone.",
    readTime: "5 MIN READ",
    difficulty: "BEGINNER",
    tags: ["INSURANCE"],
  },
  // FINANCE
  {
    slug: "credit-score-factors",
    category: "FINANCE",
    title: "What actually moves your credit score",
    excerpt: "Five factors, specific weights. Payment history is 35% alone. Most people optimize for the wrong things while ignoring the ones that matter most.",
    readTime: "6 MIN READ",
    difficulty: "BEGINNER",
    tags: ["CREDIT"],
  },
  {
    slug: "medical-bill-negotiation",
    category: "FINANCE",
    title: "Hospital bills are negotiable",
    excerpt: "The chargemaster price is fiction. Hospitals write off debt constantly. If you know the system, you can reduce a $10,000 bill to something survivable.",
    readTime: "7 MIN READ",
    difficulty: "INTERMEDIATE",
    tags: ["HEALTHCARE", "NEGOTIATION"],
  },
  {
    slug: "401k-employer-match",
    category: "FINANCE",
    title: "Your employer match is free money you might be leaving behind",
    excerpt: "A 3% employer match on a $50k salary is $1,500/year you're declining if you don't contribute enough to get it. Here's how matching works and how vesting can trap you.",
    readTime: "5 MIN READ",
    difficulty: "BEGINNER",
    tags: ["RETIREMENT", "PERSONAL FINANCE"],
  },
  {
    slug: "pay-stub-decoded",
    category: "FINANCE",
    title: "What every line on your pay stub means",
    excerpt: "Gross vs net, FICA, federal and state withholding, pre-tax deductions — most people just look at the bottom number. The rest tells you how much you're actually earning.",
    readTime: "5 MIN READ",
    difficulty: "BEGINNER",
    tags: ["TAXES", "PERSONAL FINANCE"],
  },
  {
    slug: "salary-negotiation",
    category: "FINANCE",
    title: "How to actually negotiate your salary",
    excerpt: "Most people never negotiate. The ones who do earn hundreds of thousands more over a career. The first number, the silence, the counter — it's all learnable.",
    readTime: "6 MIN READ",
    difficulty: "INTERMEDIATE",
    tags: ["NEGOTIATION", "PERSONAL FINANCE"],
  },
  {
    slug: "emergency-fund-basics",
    category: "FINANCE",
    title: "How much emergency fund you actually need, and where to put it",
    excerpt: "Not a number pulled from thin air — three to six months of essential expenses, in an account you can access same-day, not the stock market.",
    readTime: "5 MIN READ",
    difficulty: "BEGINNER",
    tags: ["PERSONAL FINANCE"],
  },
  {
    slug: "credit-freeze-vs-lock",
    category: "FINANCE",
    title: "Credit freeze vs credit lock — one is free and federally guaranteed, one isn't",
    excerpt: "A credit freeze is free by law at all three bureaus and blocks new accounts from opening in your name. A credit lock is a paid convenience product with weaker protections.",
    readTime: "5 MIN READ",
    difficulty: "BEGINNER",
    tags: ["CREDIT"],
  },
  // ELECTRICAL (additional)
  {
    slug: "surge-protector-vs-power-strip",
    category: "ELECTRICAL",
    title: "Surge protector vs power strip — they are not the same thing",
    excerpt: "A power strip just adds outlets. A surge protector absorbs voltage spikes before they reach your electronics. Plugging your computer into the wrong one won't save it.",
    readTime: "4 MIN READ",
    difficulty: "BEGINNER",
    tags: ["ELECTRICAL SAFETY"],
  },
  {
    slug: "amperage-vs-wattage",
    category: "ELECTRICAL",
    title: "Amps, volts, watts — the math that tells you what a circuit can handle",
    excerpt: "Volts times amps equals watts. That's it. Once you know that, you can figure out why your breaker trips and what you can safely plug in.",
    readTime: "5 MIN READ",
    difficulty: "BEGINNER",
    tags: ["ELECTRICAL"],
  },
  // LEGAL (additional)
  {
    slug: "miranda-rights-when",
    category: "LEGAL",
    title: "Miranda rights only apply when police do one specific thing",
    excerpt: "Getting arrested doesn't trigger Miranda. Police only have to read you your rights before a custodial interrogation — and not reading them isn't the free pass TV makes it look like.",
    readTime: "5 MIN READ",
    difficulty: "INTERMEDIATE",
    tags: ["KNOW YOUR RIGHTS"],
  },
  {
    slug: "statute-of-limitations-basics",
    category: "LEGAL",
    title: "Statute of limitations: the clock that resets if you're not careful",
    excerpt: "Old debt can become legally uncollectible — until you acknowledge it or make a partial payment, which can restart the clock in many states. Debt collectors know this even when you don't.",
    readTime: "6 MIN READ",
    difficulty: "INTERMEDIATE",
    tags: ["CIVIL LAW"],
  },
  // HEALTH (additional)
  {
    slug: "epipen-cost-alternatives",
    category: "HEALTH",
    title: "Your EpiPen alternative might be a different device entirely",
    excerpt: "Generic epinephrine auto-injectors can cost hundreds less, but some use a different mechanism than the EpiPen. Knowing which device you're holding matters in an emergency.",
    readTime: "5 MIN READ",
    difficulty: "BEGINNER",
    tags: ["MEDICATION"],
  },
  {
    slug: "telehealth-vs-urgent-care",
    category: "HEALTH",
    title: "When a video call is enough, and when it isn't",
    excerpt: "Telehealth is faster and cheaper for a huge range of problems. It's also the wrong choice for a growing number of situations that people default to it for anyway.",
    readTime: "5 MIN READ",
    difficulty: "BEGINNER",
    tags: ["HEALTHCARE"],
  },
  // HOME (additional)
  {
    slug: "space-heater-safety",
    category: "HOME",
    title: "Space heaters cause most of the deaths from home heating fires",
    excerpt: "Three feet of clearance, direct into the wall, never an extension cord. The rules are simple. Most house fires from space heaters happen because someone skipped one of them.",
    readTime: "4 MIN READ",
    difficulty: "BEGINNER",
    tags: ["HOME SAFETY"],
  },
  {
    slug: "home-inventory-for-insurance",
    category: "HOME",
    title: "Your insurance claim is only as good as your home inventory",
    excerpt: "After a fire or a break-in, you have to prove what you owned. A five-minute video walkthrough today is the difference between a paid claim and a fight.",
    readTime: "4 MIN READ",
    difficulty: "BEGINNER",
    tags: ["INSURANCE"],
  },
  // AUTO
  {
    slug: "tire-tread-penny-test",
    category: "AUTO",
    title: "The penny test for tire tread is outdated — here's the better one",
    excerpt: "Lincoln's head showing means your tires were already dangerous. The quarter test catches the problem sooner, and tread wear bars are built into every tire for a reason.",
    readTime: "4 MIN READ",
    difficulty: "BEGINNER",
    tags: ["CAR MAINTENANCE"],
  },
  {
    slug: "check-engine-light-codes",
    category: "AUTO",
    title: "That check engine light isn't automatically a $1,000 problem",
    excerpt: "Auto parts stores will read the code for free. Knowing the code before you go to a mechanic is the difference between an informed conversation and getting quoted whatever they think you'll pay.",
    readTime: "5 MIN READ",
    difficulty: "BEGINNER",
    tags: ["CAR MAINTENANCE"],
  },
  {
    slug: "extended-warranties-scam",
    category: "AUTO",
    title: "That 'your vehicle warranty is about to expire' call isn't from your dealer",
    excerpt: "Third-party vehicle service contracts are sold as warranties, aren't, and are one of the most reported scams in the country. Here's how to tell a legitimate extended warranty from a scam.",
    readTime: "6 MIN READ",
    difficulty: "INTERMEDIATE",
    tags: ["CONSUMER PROTECTION"],
  },
  {
    slug: "lemon-law-basics",
    category: "AUTO",
    title: "Lemon laws exist for exactly the car you're dealing with",
    excerpt: "A new car that's been in the shop for the same defect multiple times, or out of service too many days, may legally entitle you to a refund or replacement. Most people never file.",
    readTime: "6 MIN READ",
    difficulty: "INTERMEDIATE",
    tags: ["CONSUMER PROTECTION"],
  },
  // TECH
  {
    slug: "password-manager-2fa",
    category: "TECH",
    title: "One reused password is how your whole digital life gets taken",
    excerpt: "A password manager plus two-factor authentication closes off the two most common ways accounts get compromised. Neither takes more than twenty minutes to set up.",
    readTime: "6 MIN READ",
    difficulty: "BEGINNER",
    tags: ["DIGITAL SECURITY"],
  },
  {
    slug: "phishing-red-flags",
    category: "TECH",
    title: "The tells that give away almost every phishing attempt",
    excerpt: "Urgency, a mismatched sender address, and a link that doesn't go where the text says it does. Learn the pattern once and you'll catch it every time after.",
    readTime: "5 MIN READ",
    difficulty: "BEGINNER",
    tags: ["DIGITAL SECURITY"],
  },
  {
    slug: "data-broker-opt-out",
    category: "TECH",
    title: "Companies you've never heard of are selling your home address right now",
    excerpt: "Data brokers compile and sell your personal information legally. You can opt out of most of them — it's just not made easy, and no one tells you it's an option.",
    readTime: "7 MIN READ",
    difficulty: "INTERMEDIATE",
    tags: ["PRIVACY"],
  },
  {
    slug: "public-wifi-vpn-myths",
    category: "TECH",
    title: "The coffee shop hacker stealing your passwords isn't really the threat anymore",
    excerpt: "Most of the web is encrypted by default now, which changes what a VPN actually protects you from on public wifi. It's not nothing — it's just not what the ads say.",
    readTime: "6 MIN READ",
    difficulty: "INTERMEDIATE",
    tags: ["PRIVACY", "DIGITAL SECURITY"],
  },
  // CONSUMER
  {
    slug: "credit-card-chargebacks",
    category: "CONSUMER",
    title: "Credit card disputes and debit card disputes are not the same protection",
    excerpt: "Federal law caps your credit card fraud liability at $50 and gives you real leverage over bad merchants. Debit cards play by different rules, and the clock starts the moment the charge hits.",
    readTime: "6 MIN READ",
    difficulty: "INTERMEDIATE",
    tags: ["CONSUMER PROTECTION"],
  },
  {
    slug: "return-policy-tricks",
    category: "CONSUMER",
    title: "No law says a store has to take your return",
    excerpt: "Return policies are a courtesy, not a legal requirement, with one real federal exception. Knowing which is which changes how you shop and how you argue when a return gets denied.",
    readTime: "5 MIN READ",
    difficulty: "BEGINNER",
    tags: ["CONSUMER PROTECTION"],
  },
  {
    slug: "warranty-vs-insurance",
    category: "CONSUMER",
    title: "'Warranty void if removed' stickers are mostly illegal",
    excerpt: "A federal law from 1975 already settled this: a manufacturer can't void your warranty just because you used a third-party part or an independent repair shop, unless they can prove that part caused the problem.",
    readTime: "6 MIN READ",
    difficulty: "INTERMEDIATE",
    tags: ["CONSUMER PROTECTION"],
  },
  {
    slug: "subscription-cancellation-rights",
    category: "CONSUMER",
    title: "Why canceling a subscription is never as easy as signing up for one",
    excerpt: "It's not your imagination — some states legally require cancellation to be as easy as sign-up, but there's no federal rule yet forcing every company to comply.",
    readTime: "5 MIN READ",
    difficulty: "BEGINNER",
    tags: ["CONSUMER PROTECTION"],
  },
];

/*
 * Search-engine titles. The on-page headline stays the punchy one above; this is what goes in
 * <title> so the page matches how people actually phrase the question in Google.
 */
const seoTitles: Record<string, string> = {
  "hot-neutral-ground": "Hot, Neutral, and Ground Wires: How to Tell Them Apart",
  "right-to-remain-silent": "Do You Have to Answer Police Questions? Your Right to Stay Silent",
  "er-vs-urgent-care": "ER vs Urgent Care vs Your Doctor: Where to Go and What It Costs",
  "landlord-rights": "What Landlords Can't Legally Do: Tenant Rights Explained",
  "how-interest-works": "How Credit Card Interest Works: APR, APY, and the Minimum Payment Trap",
  "breaker-box-basics": "Breaker Box Basics: Why Breakers Trip and What You Can Fix Yourself",
  "gfci-afci-outlets": "GFCI vs AFCI: What's the Difference and Where They're Required",
  "extension-cord-gauge": "Extension Cord Gauge Explained: When a Cord Becomes a Fire Hazard",
  "outlet-replacement": "How to Replace an Electrical Outlet, Step by Step",
  "smoke-co-detector-placement": "Where to Put Smoke and Carbon Monoxide Detectors",
  "recording-police": "Is It Legal to Record the Police? Your Rights Explained",
  "small-claims-court": "How to File in Small Claims Court Without a Lawyer",
  "probable-cause": "What Is Probable Cause? Probable Cause vs Reasonable Suspicion",
  "non-compete-agreements": "Are Non-Compete Agreements Enforceable? What Courts Look At",
  "generic-vs-brand-drugs": "Are Generic Drugs as Good as Brand Name? What the FDA Requires",
  "insurance-terms-decoded": "Deductible vs Copay vs Out-of-Pocket Max, Explained",
  "prescription-cash-prices": "Why Paying Cash for Prescriptions Can Beat Your Insurance Copay",
  "reading-lab-results": "How to Read Your Blood Test Results: CBC, CMP, Lipids, A1C",
  "water-shutoff-locations": "How to Find Your Main Water Shutoff Valve (and Every Other One)",
  "lease-clauses": "Lease Clauses to Watch Out For Before You Sign",
  "mold-habitability": "Mold in Your Rental: What Your Landlord Is Required to Do",
  "renters-insurance": "What Does Renters Insurance Cover and How Much Does It Cost?",
  "credit-score-factors": "What Affects Your Credit Score: The 5 Factors and Their Weights",
  "medical-bill-negotiation": "How to Negotiate a Hospital Bill and Lower What You Owe",
  "401k-employer-match": "How a 401(k) Employer Match and Vesting Actually Work",
  "pay-stub-decoded": "How to Read Your Pay Stub: Every Line Explained",
  "salary-negotiation": "How to Negotiate Your Salary: What to Say and When",
  "emergency-fund-basics": "How Much Should Be in Your Emergency Fund, and Where to Keep It",
  "credit-freeze-vs-lock": "Credit Freeze vs Credit Lock: Which One to Use and How to Freeze",
  "surge-protector-vs-power-strip": "Surge Protector vs Power Strip: What's the Difference?",
  "amperage-vs-wattage": "Amps, Volts, and Watts: How Much Can a Circuit Handle?",
  "miranda-rights-when": "When Do Police Have to Read You Your Miranda Rights?",
  "statute-of-limitations-basics": "Statute of Limitations on Debt: How Paying Can Restart the Clock",
  "epipen-cost-alternatives": "Cheaper EpiPen Alternatives: Generic Epinephrine Auto-Injectors",
  "telehealth-vs-urgent-care": "Telehealth vs Urgent Care: When a Video Visit Is Enough",
  "space-heater-safety": "Space Heater Safety Rules That Prevent House Fires",
  "home-inventory-for-insurance": "How to Make a Home Inventory for Insurance Claims",
  "tire-tread-penny-test": "Tire Tread Depth: Penny Test vs Quarter Test and When to Replace",
  "check-engine-light-codes": "Check Engine Light On? How to Get the Code Read for Free",
  "extended-warranties-scam": "Car Warranty Expiring Calls: How to Spot the Scam",
  "lemon-law-basics": "Lemon Law Basics: Does Your Car Qualify?",
  "password-manager-2fa": "Password Manager and Two-Factor Authentication: The 20-Minute Setup",
  "phishing-red-flags": "How to Spot a Phishing Email or Text: The Red Flags",
  "data-broker-opt-out": "How to Remove Your Personal Info From Data Broker Sites",
  "public-wifi-vpn-myths": "Do You Need a VPN on Public Wi-Fi? What It Actually Protects",
  "credit-card-chargebacks": "Credit Card vs Debit Card Disputes: Your Chargeback Rights",
  "return-policy-tricks": "Do Stores Have to Accept Returns? What the Law Actually Says",
  "warranty-vs-insurance": "Does Using Third-Party Parts or Repair Shops Void Your Warranty?",
  "subscription-cancellation-rights": "Hard-to-Cancel Subscriptions: Your Rights and What Works",
  "got-scammed-what-now": "I Got Scammed — What Do I Do Now? Steps to Take Right Away",
  "sim-swap-protection": "How to Prevent SIM Swapping: Turn On Your Carrier's Number Lock",
  "back-up-your-phone": "How to Back Up Your iPhone or Android (and Your 2FA Codes)",
  "jump-start-a-car": "How to Jump-Start a Car: Cable Order, Step by Step",
  "after-a-car-accident": "What to Do After a Car Accident: Step-by-Step Checklist",
  "correct-tire-pressure": "What Should My Tire Pressure Be? Door Sticker vs Tire Sidewall",
  "dispute-credit-report-errors": "How to Dispute Credit Report Errors for Free",
  "debt-collector-rules": "What Debt Collectors Can't Do: Your Rights Under the FDCPA",
  "at-will-employment": "Can You Be Fired for No Reason? At-Will Employment Explained",
  "w2-vs-1099": "W-2 vs 1099: Self-Employment Tax and Quarterly Payments Explained",
  "health-insurance-after-job-loss": "Lost Your Job? COBRA vs Marketplace Health Insurance",
  "frozen-pipes": "How to Prevent and Thaw Frozen Pipes Safely",
};

export function seoTitle(post: Post): string {
  return seoTitles[post.slug] ?? post.title;
}

export const categories = ["ALL", "ELECTRICAL", "LEGAL", "HEALTH", "HOME", "FINANCE", "AUTO", "TECH", "CONSUMER"];

export function categorySlug(category: string): string {
  return category.toLowerCase();
}

export function categoryFromSlug(slug: string): string | undefined {
  return categories.slice(1).find(c => categorySlug(c) === slug);
}
